# Generated by Django 4.0.4 on 2022-04-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('kurs', models.CharField(blank=True, max_length=30)),
                ('raqam', models.PositiveSmallIntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(blank=True, max_length=30)),
                ('bajarilgan', models.BooleanField(default=False)),
                ('malumot', models.TextField()),
                ('raqam', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('st', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
    ]
